[package]
name = "roguelike"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]
edition = "2018"

[dependencies]
tcod = "0.13"
rand = "0.3.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
