[package]
name = "roguelike_core"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.13"

slotmap = "0.4"

rand = {version = "0.7.0", default-features = false, features = ["small_rng", "std"] }

num = "0.2"

pathfinding = "2.0"

euclid = "0.20"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

symbol = "0.1"
