[package]
name = "roguelike_engine"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ggez = { version = "0.5.1", default-features = false }
# 
# gfx_core = "*"
# gfx_device_gl = "*"
# 
# imgui = "0.2"
# imgui-gfx-renderer = "0.2"

sdl2 = { version = "0.32", features = ["image"] }

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

slotmap = "0.4"

tcod = "0.13"

noise = { version = "0.6", default-features = false }

rexpaint = "*"

symbol = "0.1"

mint = "0.5.1"

rand = {version = "0.7.0", default-features = false, features = ["small_rng", "std"] }

roguelike_core = { path = "../roguelike_core" }

